# Generated by Django 5.2.16 on 2026-07-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Require this user to choose a new password at the next opportunity.'),
        ),
    ]
