# Generated by Django 5.2.14 on 2026-05-21 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'vehicle categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_number', models.CharField(max_length=80, unique=True)),
                ('manufacturer', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('license_plate', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('announced', 'Announced'), ('checked_in', 'Checked in'), ('available', 'Available'), ('reserved', 'Reserved'), ('loaned', 'Loaned'), ('maintenance', 'Maintenance'), ('damaged', 'Damaged'), ('manufacturer_checkout', 'Manufacturer checkout'), ('archived', 'Archived')], default='announced', max_length=40)),
                ('current_odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('current_operating_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.vehiclecategory')),
            ],
            options={
                'ordering': ['internal_number'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('serial_number',), name='unique_vehicle_serial_number_when_present'), models.UniqueConstraint(condition=models.Q(('license_plate', ''), _negated=True), fields=('license_plate',), name='unique_vehicle_license_plate_when_present')],
            },
        ),
    ]
