# Generated by Django 5.2.15 on 2026-06-14 22:50

import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='qr_code',
            field=models.CharField(default=vehicles.models.generate_vehicle_qr_code, editable=False, max_length=24, unique=True),
        ),
    ]
