# Generated by Cursor on 2026-05-26

from django.db import migrations, models

from vehicles.models import generate_vehicle_qr_code


def populate_vehicle_qr_codes(apps, schema_editor):
    Vehicle = apps.get_model("vehicles", "Vehicle")
    used_codes = set(Vehicle.objects.exclude(qr_code__isnull=True).values_list("qr_code", flat=True))
    for vehicle in Vehicle.objects.filter(qr_code__isnull=True):
        qr_code = generate_vehicle_qr_code()
        while qr_code in used_codes:
            qr_code = generate_vehicle_qr_code()
        used_codes.add(qr_code)
        vehicle.qr_code = qr_code
        vehicle.save(update_fields=["qr_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="qr_code",
            field=models.CharField(blank=True, editable=False, max_length=24, null=True, unique=True),
        ),
        migrations.RunPython(populate_vehicle_qr_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="vehicle",
            name="qr_code",
            field=models.CharField(default=generate_vehicle_qr_code, editable=False, max_length=24, unique=True),
        ),
    ]
