# Generated by Django 5.2.15 on 2026-06-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='internal_number',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
    ]
