# Generated by Django 5.2.15 on 2026-06-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_internal_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='manufacturer_return_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
