# Generated by Django 5.2.16 on 2026-07-17 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def infer_meter_modes_and_backfill_archives(apps, schema_editor):
    VehicleCategory = apps.get_model("vehicles", "VehicleCategory")
    Vehicle = apps.get_model("vehicles", "Vehicle")
    for category in VehicleCategory.objects.all():
        vehicles = Vehicle.objects.filter(category_id=category.id)
        has_odometer = vehicles.filter(current_odometer_km__isnull=False).exists()
        has_hours = vehicles.filter(current_operating_hours__isnull=False).exists()
        mode = "both" if has_odometer and has_hours else ("odometer" if has_odometer else ("hours" if has_hours else "none"))
        VehicleCategory.objects.filter(pk=category.pk).update(meter_mode=mode)
    Vehicle.objects.filter(status="archived", archive_reason="").update(
        archive_reason="Legacy archive (reason unavailable)",
        archive_previous_status="manufacturer_checkout",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_sequence_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='archive_previous_status',
            field=models.CharField(blank=True, choices=[('announced', 'Announced'), ('checked_in', 'Checked in'), ('available', 'Available'), ('reserved', 'Reserved'), ('loaned', 'Loaned'), ('maintenance', 'Maintenance'), ('damaged', 'Damaged'), ('manufacturer_checkout', 'Manufacturer checkout'), ('archived', 'Archived')], max_length=40),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='external_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='meter_mode',
            field=models.CharField(choices=[('odometer', 'Odometer'), ('hours', 'Operating hours'), ('both', 'Odometer and operating hours'), ('none', 'No meter')], default='both', max_length=20),
        ),
        migrations.RunPython(infer_meter_modes_and_backfill_archives, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['external_key'], name='vehicle_external_key_idx'),
        ),
    ]
