# Generated by Django 5.2.14 on 2026-05-21 13:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('mediafiles', '0001_initial'),
        ('parties', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('operating_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('condition_notes', models.TextField(blank=True)),
                ('pdf_language', models.CharField(blank=True, max_length=10)),
                ('pdf_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mediafiles.mediafile')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_in_protocols', to=settings.AUTH_USER_MODEL)),
                ('supplier_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_in_protocols', to='parties.company')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_in_protocols', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower_name', models.CharField(blank=True, max_length=255)),
                ('borrower_phone', models.CharField(max_length=80)),
                ('expected_return_at', models.DateTimeField()),
                ('actual_return_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('checkout_odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('checkout_operating_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('return_odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('return_operating_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('checkout_notes', models.TextField(blank=True)),
                ('return_notes', models.TextField(blank=True)),
                ('checkout_pdf_language', models.CharField(blank=True, max_length=10)),
                ('return_pdf_language', models.CharField(blank=True, max_length=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='parties.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_loans', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='drivers.driver')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_loans', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturerCheckOutProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('operating_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('condition_notes', models.TextField(blank=True)),
                ('pdf_language', models.CharField(blank=True, max_length=10)),
                ('pdf_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mediafiles.mediafile')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer_checkout_protocols', to=settings.AUTH_USER_MODEL)),
                ('recipient_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_checkout_protocols', to='parties.company')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer_checkout_protocols', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
