# Generated by Django 5.2.14 on 2026-05-21 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0003_mediafile_language'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='checkout_pdf_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_checkout_documents', to='mediafiles.mediafile'),
        ),
        migrations.AddField(
            model_name='loan',
            name='return_pdf_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_return_documents', to='mediafiles.mediafile'),
        ),
    ]
