# Generated by Django 5.2.15 on 2026-06-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_loan_checkout_pdf_media_loan_return_pdf_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrower_phone',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
