# Generated by Django 5.2.16 on 2026-07-17 06:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_reservation_snapshots(apps, schema_editor):
    Reservation = apps.get_model("workflows", "Reservation")
    for reservation in Reservation.objects.select_related("driver", "company"):
        driver = reservation.driver
        company = reservation.company
        party_type = "driver" if driver else ("company" if company else "manual")
        name = reservation.reserved_for
        if not name and driver:
            name = f"{driver.first_name} {driver.last_name}".strip()
        if not name and company:
            name = company.contact_name or company.name
        phone = driver.phone if driver else (company.phone if company else "")
        Reservation.objects.filter(pk=reservation.pk).update(
            manual_phone=phone,
            snapshot={
                "schema_version": 1,
                "vehicle_id": str(reservation.vehicle_id),
                "start_at": reservation.start_at.isoformat(),
                "end_at": reservation.end_at.isoformat(),
                "party": {
                    "type": party_type,
                    "driver_id": str(reservation.driver_id) if reservation.driver_id else None,
                    "company_id": str(reservation.company_id) if reservation.company_id else None,
                    "name": name,
                    "phone": phone,
                    "company_name": company.name if company else None,
                },
                "notes": reservation.notes,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('parties', '0001_initial'),
        ('vehicles', '0006_vehicle_archive_previous_status_and_more'),
        ('workflows', '0005_hardening_snapshots_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('start_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('start_operating_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('start_snapshot', models.JSONField(blank=True, default=dict)),
                ('completion_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_operating_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('completion_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_type', models.CharField(choices=[('check_in', 'Check-in'), ('loan_checkout', 'Loan checkout'), ('loan_return', 'Loan return'), ('manufacturer_return', 'Manufacturer return'), ('reservation', 'Reservation'), ('maintenance', 'Maintenance')], max_length=40)),
                ('scope_key', models.CharField(blank=True, max_length=160)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('staged_media_ids', models.JSONField(blank=True, default=list)),
                ('step', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='return_condition_outcome',
            field=models.CharField(blank=True, choices=[('fit', 'Fit for service'), ('new_damage', 'New damage'), ('maintenance', 'Maintenance required')], max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfilled_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='loan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='workflows.loan'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='manual_phone',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='reservation',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(backfill_reservation_snapshots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled'), ('no_show', 'No-show')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'end_at'], name='reservation_status_end_idx'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_maintenance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='started_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_maintenance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='workflowdraft',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['vehicle', '-started_at'], name='maintenance_vehicle_time_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['status', '-started_at'], name='maintenance_status_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('vehicle',), name='unique_active_maintenance_per_vehicle'),
        ),
        migrations.AddIndex(
            model_name='workflowdraft',
            index=models.Index(fields=['owner', '-updated_at'], name='draft_owner_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdraft',
            index=models.Index(fields=['expires_at'], name='draft_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowdraft',
            constraint=models.UniqueConstraint(fields=('owner', 'workflow_type', 'scope_key'), name='unique_workflow_draft_scope'),
        ),
    ]
