# Generated by Django 5.2.14 on 2026-05-21 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('damages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_type', models.CharField(blank=True, max_length=80)),
                ('related_id', models.UUIDField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('signature', 'Signature'), ('pdf', 'PDF'), ('import', 'Import')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('content_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('damage_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='damages.damagereport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
