# Generated by Django 5.2.14 on 2026-05-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='language',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
