# Generated by Django 5.2.14 on 2026-05-21 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('company_type', models.CharField(choices=[('subcontractor', 'Subcontractor'), ('manufacturer', 'Manufacturer'), ('supplier', 'Supplier'), ('internal', 'Internal')], max_length=30)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'company_type'), name='unique_company_name_type')],
            },
        ),
    ]
