"""Media metadata records."""

from __future__ import annotations

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _

from config.models import TimeStampedUUIDModel


class MediaType(models.TextChoices):
    PHOTO = "photo", _("Photo")
    SIGNATURE = "signature", _("Signature")
    PDF = "pdf", _("PDF")
    IMPORT = "import", _("Import")


class MediaFile(TimeStampedUUIDModel):
    vehicle = models.ForeignKey("vehicles.Vehicle", on_delete=models.SET_NULL, null=True, blank=True, related_name="media_files")
    loan = models.ForeignKey("workflows.Loan", on_delete=models.SET_NULL, null=True, blank=True, related_name="media_files")
    damage_report = models.ForeignKey(
        "damages.DamageReport", on_delete=models.SET_NULL, null=True, blank=True, related_name="media_files"
    )
    related_type = models.CharField(max_length=80, blank=True)
    related_id = models.UUIDField(null=True, blank=True)
    media_type = models.CharField(max_length=20, choices=MediaType.choices)
    original_filename = models.CharField(max_length=255)
    storage_key = models.CharField(max_length=500, unique=True)
    content_type = models.CharField(max_length=120)
    size_bytes = models.PositiveBigIntegerField()
    content_sha256 = models.CharField(max_length=64, blank=True, default="")
    language = models.CharField(max_length=10, blank=True)
    is_generated = models.BooleanField(default=False)
    attached_at = models.DateTimeField(null=True, blank=True)
    uploaded_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name="media_files")

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["media_type", "-created_at"], name="media_type_created_idx"),
            models.Index(fields=["related_type", "related_id"], name="media_related_idx"),
            models.Index(fields=["uploaded_by", "attached_at"], name="media_staging_owner_idx"),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=["related_type", "related_id", "language"],
                condition=Q(media_type="pdf", is_generated=True),
                name="unique_pdf_record_type_language",
            ),
        ]

    def __str__(self) -> str:
        return self.original_filename

    def clean(self):
        errors = {}
        if self.size_bytes <= 0:
            errors["size_bytes"] = _("File size must be greater than zero.")
        if len(self.content_sha256 or "") != 64:
            errors["content_sha256"] = _("A SHA-256 content digest is required.")

        relation_values = [
            self.vehicle_id,
            self.loan_id,
            self.damage_report_id,
            self.related_type,
            self.related_id,
        ]
        is_staged = not any(relation_values)
        if not is_staged and (not self.related_type or not self.related_id):
            errors["related_type"] = _("Attached media requires a typed related record.")
        if not is_staged and self.related_type and self.related_id and not self._target_matches():
            errors["related_id"] = _("The media attachment target is inconsistent.")
        if self.loan_id:
            if not self.vehicle_id or self.loan.vehicle_id != self.vehicle_id:
                errors["loan"] = _("The loan and media must belong to the same vehicle.")
        if self.damage_report_id:
            if not self.vehicle_id or self.damage_report.vehicle_id != self.vehicle_id:
                errors["damage_report"] = _("The damage report and media must belong to the same vehicle.")
            if self.loan_id and self.damage_report.loan_id not in {None, self.loan_id}:
                errors["damage_report"] = _("The damage report and media must belong to the same loan.")
        if self.media_type == MediaType.PDF:
            if not self.is_generated:
                errors["media_type"] = _("PDF media can only be generated by the server.")
            if not self.language:
                errors["language"] = _("Generated PDFs require a language.")
        elif self.language:
            errors["language"] = _("Only generated PDFs may have a document language.")
        if self.is_generated and self.media_type != MediaType.PDF:
            errors["is_generated"] = _("Only PDF media can be server generated.")
        if errors:
            raise ValidationError(errors)

    def save(self, *args, **kwargs):
        previous = type(self).objects.filter(pk=self.pk).first() if self.pk else None
        if previous:
            immutable_fields = (
                "media_type",
                "original_filename",
                "storage_key",
                "content_type",
                "size_bytes",
                "content_sha256",
                "language",
                "is_generated",
                "uploaded_by_id",
            )
            changed = [field for field in immutable_fields if getattr(previous, field) != getattr(self, field)]
            old_relation = previous._relation_identity()
            new_relation = self._relation_identity()
            if changed:
                raise ValidationError(_("Stored media metadata is immutable."))
            if old_relation != new_relation and not (previous.is_staged and not self.is_staged):
                raise ValidationError(_("Attached media cannot be reassociated."))
            if previous.attached_at and self.attached_at != previous.attached_at:
                raise ValidationError(_("The media attachment timestamp is immutable."))
        if not self.is_staged and self.attached_at is None:
            from django.utils import timezone

            self.attached_at = timezone.now()
        self.full_clean()
        return super().save(*args, **kwargs)

    @property
    def is_staged(self) -> bool:
        return not any(self._relation_identity())

    def _relation_identity(self):
        return (
            self.vehicle_id,
            self.loan_id,
            self.damage_report_id,
            self.related_type,
            self.related_id,
        )

    def _target_matches(self) -> bool:
        if self.related_type == "vehicle":
            return self.vehicle_id is not None and self.related_id == self.vehicle_id
        if self.related_type in {"loan_checkout", "loan_return", "loan_checkout_pdf", "loan_return_pdf"}:
            return (
                self.vehicle_id is not None
                and self.loan_id is not None
                and self.related_id == self.loan_id
                and self.loan.vehicle_id == self.vehicle_id
            )
        if self.related_type == "damage_report":
            return (
                self.vehicle_id is not None
                and self.damage_report_id is not None
                and self.related_id == self.damage_report_id
            )
        if self.related_type in {"check_in_protocol", "check_in_protocol_pdf"}:
            from workflows.models import CheckInProtocol

            return bool(
                self.vehicle_id
                and CheckInProtocol.objects.filter(pk=self.related_id, vehicle_id=self.vehicle_id).exists()
            )
        if self.related_type in {
            "manufacturer_checkout_protocol",
            "manufacturer_checkout_protocol_pdf",
        }:
            from workflows.models import ManufacturerCheckOutProtocol

            return bool(
                self.vehicle_id
                and ManufacturerCheckOutProtocol.objects.filter(
                    pk=self.related_id,
                    vehicle_id=self.vehicle_id,
                ).exists()
            )
        if self.related_type in {"maintenance_start", "maintenance_complete"}:
            from workflows.models import MaintenanceRecord

            return bool(
                self.vehicle_id
                and MaintenanceRecord.objects.filter(
                    pk=self.related_id,
                    vehicle_id=self.vehicle_id,
                ).exists()
            )
        if self.related_type == "vehicle_import":
            from imports.models import ImportJob

            return ImportJob.objects.filter(pk=self.related_id, source_media_id=self.pk).exists()
        return False

    def delete(self, *args, **kwargs):
        if not self.is_staged or self.media_type in {MediaType.PDF, MediaType.IMPORT}:
            raise ValidationError(_("Attached and generated media cannot be deleted."))
        return super().delete(*args, **kwargs)
