"""Storage and validation helpers for media files."""

from __future__ import annotations

import hashlib
import logging
from datetime import timedelta
from pathlib import Path
from uuid import uuid4

from django.conf import settings
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.db import transaction
from django.db.models import Sum
from django.utils import timezone
from django.utils.text import get_valid_filename
from django.utils.translation import gettext as _
from rest_framework import serializers

from audit.services import audit_event
from mediafiles.models import MediaFile, MediaType


logger = logging.getLogger("fleet")


_ALLOWED_UPLOADS = {
    MediaType.PHOTO: {
        "extensions": {".jpg", ".jpeg", ".png", ".gif", ".webp"},
        "content_types": {"image/jpeg", "image/png", "image/gif", "image/webp"},
    },
    MediaType.SIGNATURE: {
        "extensions": {".jpg", ".jpeg", ".png", ".webp"},
        "content_types": {"image/jpeg", "image/png", "image/webp"},
    },
    MediaType.PDF: {
        "extensions": {".pdf"},
        "content_types": {"application/pdf"},
    },
    MediaType.IMPORT: {
        "extensions": {".xlsx", ".xlsm"},
        # Browsers and operating systems are inconsistent about the content type
        # they attach to .xlsx uploads (often a generic octet-stream or zip). The
        # ZIP magic-byte prefix is verified separately, so we accept the common
        # generic types here instead of rejecting otherwise-valid spreadsheets.
        "content_types": {
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "application/vnd.ms-excel.sheet.macroEnabled.12",
            "application/vnd.ms-excel",
            "application/octet-stream",
            "application/zip",
            "application/x-zip-compressed",
        },
    },
}


@transaction.atomic
def create_media_file_from_upload(
    *,
    uploaded_file,
    actor,
    media_type: str,
    vehicle=None,
    loan=None,
    damage_report=None,
    related_type: str = "",
    related_id=None,
    language: str = "",
    request_meta: dict[str, str] | None = None,
    internal: bool = False,
) -> MediaFile:
    """Validate and persist an uploaded file under MEDIA_ROOT."""
    if media_type == MediaType.PDF:
        raise serializers.ValidationError({"media_type": _("PDF media can only be generated by the server.")})
    if not internal and any((vehicle, loan, damage_report, related_type, related_id, language)):
        raise serializers.ValidationError(
            {"detail": _("Uploads must be staged before they are attached to a domain record.")}
        )
    filename = _clean_filename(getattr(uploaded_file, "name", "upload"))
    content_type = _normalized_content_type(getattr(uploaded_file, "content_type", ""))
    size_bytes = int(getattr(uploaded_file, "size", 0) or 0)
    _validate_file(
        media_type=media_type,
        filename=filename,
        content_type=content_type,
        size_bytes=size_bytes,
        prefix=_file_prefix(uploaded_file),
    )
    if media_type in {MediaType.PHOTO, MediaType.SIGNATURE}:
        # Serialize staged quota checks per uploader. Without a stable row lock,
        # concurrent uploads could all observe the same pre-upload count.
        type(actor).objects.select_for_update().only("pk").get(pk=actor.pk)
        _enforce_staged_quota(actor=actor, incoming_size=size_bytes)
    content_sha256 = _upload_sha256(uploaded_file)
    try:
        uploaded_file.seek(0)
    except (AttributeError, OSError):
        pass

    storage_key = _storage_key(media_type=media_type, filename=filename)
    saved_key = default_storage.save(storage_key, uploaded_file)
    try:
        media = MediaFile.objects.create(
            vehicle=vehicle,
            loan=loan,
            damage_report=damage_report,
            related_type=related_type,
            related_id=related_id,
            media_type=media_type,
            original_filename=filename,
            storage_key=saved_key,
            content_type=content_type,
            size_bytes=size_bytes,
            content_sha256=content_sha256,
            language=language,
            uploaded_by=actor,
        )
        audit_event(
            actor=actor,
            action="media.uploaded",
            entity_type="media_file",
            entity_id=media.id,
            after={"media_type": media.media_type, "size_bytes": media.size_bytes, "sha256": media.content_sha256},
            request_meta=request_meta,
        )
        return media
    except Exception:
        cleanup_storage_file(saved_key)
        raise
    finally:
        try:
            uploaded_file.seek(0)
        except (AttributeError, OSError):
            pass


def create_media_file_from_bytes(
    *,
    content: bytes,
    actor,
    media_type: str,
    filename: str,
    content_type: str,
    vehicle=None,
    loan=None,
    damage_report=None,
    related_type: str = "",
    related_id=None,
    language: str = "",
    request_meta: dict[str, str] | None = None,
) -> MediaFile:
    """Persist generated media content and metadata."""
    clean_filename = _clean_filename(filename)
    normalized_content_type = _normalized_content_type(content_type)
    _validate_file(
        media_type=media_type,
        filename=clean_filename,
        content_type=normalized_content_type,
        size_bytes=len(content),
        prefix=content[:16],
    )
    storage_key = _storage_key(media_type=media_type, filename=clean_filename)
    saved_key = default_storage.save(storage_key, ContentFile(content))
    try:
        media = MediaFile.objects.create(
            vehicle=vehicle,
            loan=loan,
            damage_report=damage_report,
            related_type=related_type,
            related_id=related_id,
            media_type=media_type,
            original_filename=clean_filename,
            storage_key=saved_key,
            content_type=normalized_content_type,
            size_bytes=len(content),
            content_sha256=hashlib.sha256(content).hexdigest(),
            language=language,
            is_generated=media_type == MediaType.PDF,
            uploaded_by=actor,
        )
        audit_event(
            actor=actor,
            action="pdf.generated" if media_type == MediaType.PDF else "media.generated",
            entity_type="media_file",
            entity_id=media.id,
            after={
                "media_type": media.media_type,
                "related_type": media.related_type,
                "related_id": str(media.related_id) if media.related_id else None,
                "language": media.language,
                "sha256": media.content_sha256,
            },
            request_meta=request_meta,
        )
        return media
    except Exception:
        cleanup_storage_file(saved_key)
        raise


def cleanup_storage_file(storage_key: str) -> None:
    """Best-effort cleanup without masking the transaction's original error."""
    try:
        default_storage.delete(storage_key)
    except Exception:  # pragma: no cover - depends on an unavailable external backend
        logger.exception("Failed to clean up media storage object %s", storage_key)


@transaction.atomic
def expire_staged_media(*, actor=None, cutoff=None) -> int:
    """Delete expired, unattached user uploads under row locks."""
    cutoff = cutoff or (timezone.now() - timedelta(hours=int(settings.STAGED_MEDIA_TTL_HOURS)))
    queryset = MediaFile.objects.select_for_update().filter(
        attached_at__isnull=True,
        created_at__lt=cutoff,
        media_type__in=[MediaType.PHOTO, MediaType.SIGNATURE],
    )
    # Draft-held media remains staged by design, but must survive until the
    # owning draft is discarded or expires.
    try:
        from workflows.drafts import active_draft_media_ids

        held_ids = active_draft_media_ids()
        if held_ids:
            queryset = queryset.exclude(pk__in=held_ids)
    except ImportError:  # pragma: no cover - only during partial migrations
        pass
    if actor is not None:
        queryset = queryset.filter(uploaded_by=actor)

    expired = list(queryset)
    for media in expired:
        storage_key = media.storage_key
        audit_event(
            actor=actor,
            action="media.expired",
            entity_type="media_file",
            entity_id=media.id,
            before={
                "media_type": media.media_type,
                "size_bytes": media.size_bytes,
                "sha256": media.content_sha256,
                "uploaded_by_id": str(media.uploaded_by_id),
            },
        )
        media.delete()
        transaction.on_commit(lambda key=storage_key: cleanup_storage_file(key))
    return len(expired)


def validate_existing_media_file(media: MediaFile) -> None:
    """Ensure metadata points to a stored file before serving it."""
    if not default_storage.exists(media.storage_key):
        raise serializers.ValidationError({"detail": _("Stored media file is missing.")})
    if media.content_sha256:
        digest = hashlib.sha256()
        with default_storage.open(media.storage_key, "rb") as stored:
            while chunk := stored.read(1024 * 1024):
                digest.update(chunk)
        if digest.hexdigest() != media.content_sha256:
            raise serializers.ValidationError({"detail": _("Stored media content failed its integrity check.")})


@transaction.atomic
def attach_media_files(
    *,
    media_files,
    actor,
    vehicle,
    related_type: str,
    related_id,
    loan=None,
    damage_report=None,
    allowed_types: set[str] | None = None,
    request_meta: dict[str, str] | None = None,
) -> list[MediaFile]:
    """Attach actor-owned staged media exactly once under a row lock."""

    ids = [getattr(item, "pk", item) for item in media_files]
    if not ids:
        return []
    allowed_types = allowed_types or {MediaType.PHOTO, MediaType.SIGNATURE}
    locked = list(MediaFile.objects.select_for_update().filter(pk__in=ids))
    if len(locked) != len(set(ids)):
        raise serializers.ValidationError({"media_file_ids": _("One or more media files are unavailable.")})
    attached = []
    for media in locked:
        if media.media_type not in allowed_types:
            raise serializers.ValidationError(
                {"media_file_ids": _("This media type cannot be attached to the requested record.")}
            )
        if media.uploaded_by_id != actor.pk:
            raise serializers.ValidationError({"media_file_ids": _("You may only attach media that you uploaded.")})
        if not media.is_staged:
            raise serializers.ValidationError({"media_file_ids": _("Media can only be attached once.")})
        validate_existing_media_file(media)
        _validate_attachment_target(
            vehicle=vehicle,
            loan=loan,
            damage_report=damage_report,
            related_type=related_type,
            related_id=related_id,
        )
        media.vehicle = vehicle
        media.loan = loan
        media.damage_report = damage_report
        media.related_type = related_type
        media.related_id = related_id
        media.save(
            update_fields=[
                "vehicle",
                "loan",
                "damage_report",
                "related_type",
                "related_id",
                "attached_at",
                "updated_at",
            ]
        )
        audit_event(
            actor=actor,
            action="media.attached",
            entity_type="media_file",
            entity_id=media.id,
            after={
                "vehicle_id": str(vehicle.id) if vehicle else None,
                "loan_id": str(loan.id) if loan else None,
                "damage_report_id": str(damage_report.id) if damage_report else None,
                "related_type": related_type,
                "related_id": str(related_id),
            },
            request_meta=request_meta,
        )
        attached.append(media)
    return attached


def _validate_attachment_target(*, vehicle, loan, damage_report, related_type: str, related_id) -> None:
    if related_type == "vehicle_import":
        from imports.models import ImportJob

        if not ImportJob.objects.filter(pk=related_id).exists():
            raise serializers.ValidationError({"media_file_ids": _("The media attachment target is inconsistent.")})
        return
    if vehicle is None:
        raise serializers.ValidationError({"media_file_ids": _("A vehicle is required for operational media.")})
    if loan is not None and loan.vehicle_id != vehicle.id:
        raise serializers.ValidationError({"media_file_ids": _("The loan and media must belong to the same vehicle.")})
    if damage_report is not None:
        if damage_report.vehicle_id != vehicle.id:
            raise serializers.ValidationError(
                {"media_file_ids": _("The damage report and media must belong to the same vehicle.")}
            )
        if loan is not None and damage_report.loan_id not in {None, loan.id}:
            raise serializers.ValidationError(
                {"media_file_ids": _("The damage report and media must belong to the same loan.")}
            )
    expected_id = None
    if related_type == "vehicle":
        expected_id = vehicle.id
    elif related_type in {"loan_checkout", "loan_return"} and loan is not None:
        expected_id = loan.id
    elif related_type == "damage_report" and damage_report is not None:
        expected_id = damage_report.id
    elif related_type == "check_in_protocol":
        from workflows.models import CheckInProtocol

        expected_id = (
            CheckInProtocol.objects.filter(pk=related_id, vehicle=vehicle).values_list("pk", flat=True).first()
        )
    elif related_type == "manufacturer_checkout_protocol":
        from workflows.models import ManufacturerCheckOutProtocol

        expected_id = (
            ManufacturerCheckOutProtocol.objects.filter(pk=related_id, vehicle=vehicle)
            .values_list("pk", flat=True)
            .first()
        )
    elif related_type in {"maintenance_start", "maintenance_complete"}:
        from workflows.models import MaintenanceRecord

        expected_id = (
            MaintenanceRecord.objects.filter(pk=related_id, vehicle=vehicle)
            .values_list("pk", flat=True)
            .first()
        )
    if expected_id != related_id:
        raise serializers.ValidationError({"media_file_ids": _("The media attachment target is inconsistent.")})


def _enforce_staged_quota(*, actor, incoming_size: int) -> None:
    expire_staged_media(actor=actor)

    # Count every remaining staged file. This keeps the quota fail-closed even
    # if an old row could not be selected by a previous cleanup attempt.
    staged = MediaFile.objects.filter(uploaded_by=actor, attached_at__isnull=True)
    if staged.count() >= int(settings.MAX_STAGED_MEDIA_FILES):
        raise serializers.ValidationError({"file": _("The staged upload file quota has been reached.")})
    current_size = staged.aggregate(total=Sum("size_bytes"))["total"] or 0
    max_size = int(settings.MAX_STAGED_MEDIA_SIZE_MB) * 1024 * 1024
    if current_size + incoming_size > max_size:
        raise serializers.ValidationError({"file": _("The staged upload size quota has been reached.")})


def _validate_file(*, media_type: str, filename: str, content_type: str, size_bytes: int, prefix: bytes) -> None:
    if media_type not in _ALLOWED_UPLOADS:
        raise serializers.ValidationError({"media_type": _("Unsupported media type.")})
    if size_bytes <= 0:
        raise serializers.ValidationError({"file": _("File must not be empty.")})
    max_size = int(getattr(settings, "MAX_UPLOAD_SIZE_MB", 25)) * 1024 * 1024
    if size_bytes > max_size:
        raise serializers.ValidationError(
            {"file": _("File exceeds the maximum upload size of %(size)d MB.") % {"size": settings.MAX_UPLOAD_SIZE_MB}}
        )

    rules = _ALLOWED_UPLOADS[media_type]
    extension = Path(filename).suffix.lower()
    if extension not in rules["extensions"]:
        raise serializers.ValidationError({"file": _("File extension is not allowed for this media type.")})
    if content_type not in rules["content_types"]:
        raise serializers.ValidationError({"file": _("File content type is not allowed for this media type.")})
    if not _prefix_matches(media_type=media_type, extension=extension, prefix=prefix):
        raise serializers.ValidationError({"file": _("File content does not match the selected media type.")})


def _prefix_matches(*, media_type: str, extension: str, prefix: bytes) -> bool:
    if media_type in {MediaType.PHOTO, MediaType.SIGNATURE}:
        if extension in {".jpg", ".jpeg"}:
            return prefix.startswith(bytes.fromhex("ffd8ff"))
        if extension == ".png":
            return prefix.startswith(bytes.fromhex("89504e470d0a1a0a"))
        if extension == ".gif":
            return prefix.startswith((b"GIF87a", b"GIF89a"))
        if extension == ".webp":
            return len(prefix) >= 12 and prefix.startswith(b"RIFF") and prefix[8:12] == b"WEBP"
    if media_type == MediaType.PDF:
        return prefix.startswith(b"%PDF")
    if media_type == MediaType.IMPORT:
        return prefix.startswith(bytes.fromhex("504b0304"))
    return False


def _file_prefix(uploaded_file) -> bytes:
    try:
        uploaded_file.seek(0)
    except (AttributeError, OSError):
        pass
    prefix = uploaded_file.read(16)
    if isinstance(prefix, str):
        prefix = prefix.encode()
    try:
        uploaded_file.seek(0)
    except (AttributeError, OSError):
        pass
    return prefix or b""


def _upload_sha256(uploaded_file) -> str:
    digest = hashlib.sha256()
    try:
        uploaded_file.seek(0)
    except (AttributeError, OSError):
        pass
    chunks = getattr(uploaded_file, "chunks", None)
    if chunks:
        for chunk in chunks():
            digest.update(chunk)
    else:
        while chunk := uploaded_file.read(1024 * 1024):
            digest.update(chunk)
    try:
        uploaded_file.seek(0)
    except (AttributeError, OSError):
        pass
    return digest.hexdigest()


def _storage_key(*, media_type: str, filename: str) -> str:
    now = timezone.now()
    extension = Path(filename).suffix.lower()
    return f"{media_type}/{now:%Y/%m/%d}/{uuid4().hex}{extension}"


def _clean_filename(filename: str) -> str:
    name = get_valid_filename(Path(filename or "upload").name)
    return name or "upload"


def _normalized_content_type(content_type: str) -> str:
    return (content_type or "application/octet-stream").split(";", 1)[0].strip().lower()
