# Generated by Django 5.2.14 on 2026-05-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='workflow_phase',
            field=models.CharField(choices=[('general', 'General'), ('check_in', 'Check-in'), ('loan_checkout', 'Loan checkout'), ('loan_return', 'Loan return'), ('manufacturer_checkout', 'Manufacturer check-out')], default='general', max_length=40),
        ),
    ]
