# Generated by Django 5.2.14 on 2026-05-21 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_type', models.CharField(choices=[('vehicles', 'Vehicles'), ('drivers', 'Drivers'), ('companies', 'Companies')], max_length=30)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('failed', 'Failed'), ('committed', 'Committed')], default='uploaded', max_length=20)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_count', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
