# Generated by Django 5.2.14 on 2026-05-21 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='source_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_jobs', to='mediafiles.mediafile'),
        ),
    ]
